name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: |
        cargo check --verbose
        cargo fmt -- --check
    - name: Compile
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
